name: Release
on:
  push:
    branches:
      - stable
jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
      upload_url: ${{ steps.release.outputs.upload_url }}
    steps:
      - uses: actions/checkout@v2 
      - uses: GoogleCloudPlatform/release-please-action@v2
        id: release
        with:
          package-name: NetMon
          release-type: rust
  linux-x86_64:
    runs-on: ubuntu-latest
    needs: release
    if: ${{ needs.release.outputs.release_created }}
    steps:
      - uses: actions/checkout@v1
      - name: Build binaries
        run: |
          rustup update
          cargo build --release
      - name: Package binaries
        run: |
          cd target/release
          strip netmon-server
          strip netmon-client
          chmod +x netmon-server
          chmod +x netmon-client
          tar -c netmon-server | gzip > netmon-server.tar.gz
          tar -c netmon-client | gzip > netmon-client.tar.gz
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          asset_name: netmon-server-${{ needs.release.outputs.tag_name }}-linux-x86_64.tar.gz
          asset_content_type: application/gzip
          asset_path: target/release/netmon-server.tar.gz
          upload_url: ${{ needs.release.outputs.upload_url }}
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          asset_name: netmon-client-${{ needs.release.outputs.tag_name }}-linux-x86_64.tar.gz
          asset_content_type: application/gzip
          asset_path: target/release/netmon-client.tar.gz
          upload_url: ${{ needs.release.outputs.upload_url }}
  windows-x86_64:
    runs-on: windows-latest
    needs: release
    if: ${{ needs.release.outputs.release_created }}
    steps:
      - uses: actions/checkout@v1
      - name: Build binaries
        run: |
          rustup update
          cargo build --release
      - name: Package binaries
        run: |
          cd target/release
          7z a netmon-server.7z netmon-server.exe
          7z a netmon-client.7z netmon-client.exe
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          asset_name: netmon-server-${{ needs.release.outputs.tag_name }}-windows-x86_64.7z
          asset_content_type: application/x-7z-compressed
          asset_path: target/release/netmon-server.7z
          upload_url: ${{ needs.release.outputs.upload_url }}
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          asset_name: netmon-client-${{ needs.release.outputs.tag_name }}-windows-x86_64.7z
          asset_content_type: application/x-7z-compressed
          asset_path: target/release/netmon-client.7z
          upload_url: ${{ needs.release.outputs.upload_url }}

