name: Release Please

on:
  push:
    branches:
      - stable

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: cargo test --verbose
      - uses: GoogleCloudPlatform/release-please-action@v2
      - name: Release
        with:
          package-name: NetMon
          release-type: rust
