name: upload-binaries

on:
  release:
    types:
      - created

jobs:
  linux-x86_64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Build binaries
        run: |
          rustup update
          cargo build --release

      - name: Package binaries
        run: |
          cd target/release
          strip netmon-server
          strip netmon-client
          chmod +x netmon-server
          chmod +x netmon-client
          tar -c netmon-server | gzip > netmon-server.tar.gz
          tar -c netmon-client | gzip > netmon-client.tar.gz

      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          asset_name: netmon-server-${{ github.event.release.tag-name }}-linux-x86_64.tar.gz
          asset_content_type: application/gzip
          asset_path: target/release/netmon-server.tar.gz
          upload_url: ${{ github.event.release.upload_url }}

      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          asset_name: netmon-client-${{ github.event.release.tag-name }}-linux-x86_64.tar.gz
          asset_content_type: application/gzip
          asset_path: target/release/netmon-client.tar.gz
          upload_url: ${{ github.event.release.upload_url }}

  windows-x86_64:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1

      - name: Build binaries
        run: |
          rustup update
          cargo build --release

      - name: Package binaries
        run: |
          cd target/release
          7z a netmon-server.7z netmon-server.exe
          7z a netmon-client.7z netmon-client.exe
      
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          asset_name: netmon-server-${{ github.event.release.tag-name }}-windows-x86_64.7z
          asset_content_type: application/x-7z-compressed
          asset_path: target/release/netmon-server.7z
          upload_url: ${{ github.event.release.upload_url }}

      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          asset_name: netmon-client-${{ github.event.release.tag-name }}-windows-x86_64.7z
          asset_content_type: application/x-7z-compressed
          asset_path: target/release/netmon-client.7z
          upload_url: ${{ github.event.release.upload_url }}
